import AsyncStorage from '@react-native-async-storage/async-storage';
import createContextHook from '@nkzw/create-context-hook';
import { useState, useEffect } from 'react';

export type Language = 'ar' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string, fallback?: string) => string;
}

const translations = {
  ar: {
    'app.title': 'مساعد الذكاء الاصطناعي',
    'login.title': 'تسجيل الدخول',
    'login.username': 'اسم المستخدم',
    'login.password': 'كلمة المرور',
    'login.submit': 'دخول',
    'login.error': 'اسم المستخدم أو كلمة المرور غير صحيحة',
    'chat.newChat': 'محادثة جديدة',
    'chat.placeholder': 'اكتب رسالتك هنا...',
    'chat.send': 'إرسال',
    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.logout': 'تسجيل الخروج',
    'features.title': 'الميزات',
    'features.general': 'القدرات العامة',
    'features.content': 'إنشاء المحتوى الإبداعي',
    'features.media': 'تحليل وسائط المتعددة',
    'features.special': 'قدرات خاصة',
    'features.files': 'إدارة الملفات',
    'notFound.title': 'عفوا!',
    'notFound.message': 'هذه الشاشة غير موجودة.',
    'notFound.link': 'الذهاب إلى الشاشة الرئيسية!',
    'settings.logoutConfirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'settings.cancel': 'إلغاء',
    'settings.profile.title': 'الملف الشخصي',
    'settings.profile.notSet': 'غير محدد',
    'settings.wip': 'ميزة قيد التطوير',
    'settings.languageSelect': 'اختر اللغة',
    'settings.languageAr': 'العربية',
    'settings.languageEn': 'English',
    'settings.notifications.title': 'الإشعارات',
    'settings.notifications.subtitle': 'إدارة الإشعارات والتنبيهات',
    'settings.privacy.title': 'الخصوصية والأمان',
    'settings.privacy.subtitle': 'إعدادات الخصوصية والحماية',
    'settings.about.title': 'حول التطبيق',
    'settings.about.subtitle': 'معلومات التطبيق والإصدار',
    'settings.about.description': 'مساعد الذكاء الاصطناعي\nالإصدار 1.0.0\n\nتطبيق ذكي متقدم يوفر مساعدة شاملة في مختلف المجالات باستخدام تقنيات الذكاء الاصطناعي المتطورة.',
    'settings.header.subtitle': 'إدارة إعدادات التطبيق والحساب',
    'settings.user.defaultName': 'المستخدم',
    'settings.user.admin': 'مدير النظام',
    'settings.user.user': 'مستخدم',
    'settings.general': 'الإعدادات العامة',
    'settings.footer.developedBy': 'تم التطوير بواسطة فريق التطوير',
    'chat.deleteSession.title': 'حذف المحادثة',
    'chat.deleteSession.message': 'هل أنت متأكد أنك تريد حذف هذه المحادثة؟',
    'chat.deleteSession.cancel': 'إلغاء',
    'chat.deleteSession.delete': 'حذف',
    'chat.permissions.mediaLibrary.title': 'الإذن مطلوب',
    'chat.permissions.mediaLibrary.message': 'يرجى منح أذونات مكتبة الوسائط لاختيار صورة.',
    'chat.errors.readDocument.title': 'خطأ',
    'chat.errors.readDocument.message': 'تعذر قراءة المستند المحدد.',
    'chat.permissions.microphone.title': 'الإذن مطلوب',
    'chat.permissions.microphone.message': 'يرجى منح أذونات الميكروفون لتسجيل الصوت.',
    'chat.errors.startRecording.title': 'خطأ في التسجيل',
    'chat.errors.startRecording.message': 'فشل بدء التسجيل. يرجى المحاولة مرة أخرى.',
    'chat.errors.getRecordingUri.title': 'خطأ في التسجيل',
    'chat.errors.getRecordingUri.message': 'فشل في الحصول على URI التسجيل.',
    'chat.errors.stopRecording.title': 'خطأ في التسجيل',
    'chat.errors.stopRecording.message': 'فشل إيقاف التسجيل. يرجى المحاولة مرة أخرى.',
    'chat.permissions.camera.title': 'الإذن مطلوب',
    'chat.permissions.camera.message': 'يرجى منح أذونات الكاميرا لالتقاط صورة.',
    'chat.attachments.title': 'إرفاق ملف',
    'chat.attachments.message': 'اختر نوع المرفق',
    'chat.attachments.gallery': 'صورة من المعرض',
    'chat.attachments.camera': 'التقاط صورة',
    'chat.attachments.file': 'ملف',
    'chat.attachments.cancel': 'إلغاء',
    'features.comingSoon': 'قريباً',
    'chat.thinking': 'جاري التفكير...',
    'chat.audioMessage': 'رسالة صوتية',
    'chat.attachedFile': 'ملف مرفق',
    'chat.searchResults': 'نتائج البحث',
    'chat.codeOutput': 'النتيجة:',
    'chat.imagePrompt': 'الوصف:',
    'chat.analysisTitle': 'تحليل',
    'chat.analysisTypeContent': 'المحتوى',
    'chat.you': 'أنت',
    'chat.assistant': 'المساعد',
    'agent.general.name': 'المساعد العام',
    'agent.general.description': 'مساعد ذكي شامل للمحادثة العامة والاستفسارات المتنوعة',
    'agent.general.capabilities.0': 'المحادثة الطبيعية',
    'agent.general.capabilities.1': 'الإجابة على الأسئلة العامة',
    'agent.general.capabilities.2': 'تقديم المساعدة والنصائح',
    'agent.general.capabilities.3': 'الترجمة البسيطة',
    'agent.general.capabilities.4': 'العمليات الحسابية الأساسية',
    'agent.general.systemPrompt': 'أنت مساعد ذكي مفيد وودود. تجيب على الأسئلة بوضوح وتقدم المساعدة في مختلف المواضيع.',
    'agent.web_search.name': 'باحث الويب',
    'agent.web_search.description': 'متخصص في البحث عن المعلومات الحديثة على الإنترنت',
    'agent.web_search.capabilities.0': 'البحث في الإنترنت',
    'agent.web_search.capabilities.1': 'جمع المعلومات الحديثة',
    'agent.web_search.capabilities.2': 'التحقق من الحقائق',
    'agent.web_search.capabilities.3': 'البحث الأكاديمي',
    'agent.web_search.capabilities.4': 'تتبع الأخبار والأحداث',
    'agent.web_search.systemPrompt': 'أنت خبير في البحث على الإنترنت. تبحث عن المعلومات الدقيقة والحديثة وتقدمها بشكل منظم مع ذكر المصادر.',
    'agent.image_generator.name': 'مولد الصور',
    'agent.image_generator.description': 'ينشئ صور فنية وتصاميم بناءً على الوصف النصي',
    'agent.image_generator.capabilities.0': 'إنشاء الصور من النص',
    'agent.image_generator.capabilities.1': 'التصميم الفني',
    'agent.image_generator.capabilities.2': 'الرسوم التوضيحية',
    'agent.image_generator.capabilities.3': 'تعديل الصور',
    'agent.image_generator.capabilities.4': 'إنشاء الشعارات',
    'agent.image_generator.systemPrompt': 'أنت فنان رقمي متخصص في إنشاء الصور. تحول الأوصاف النصية إلى صور جميلة ومعبرة.',
    'agent.code_analyst.name': 'محلل الأكواد',
    'agent.code_analyst.description': 'خبير في البرمجة وتحليل الأكواد وحل المشاكل التقنية',
    'agent.code_analyst.capabilities.0': 'تحليل الأكواد',
    'agent.code_analyst.capabilities.1': 'إصلاح الأخطاء',
    'agent.code_analyst.capabilities.2': 'كتابة البرامج',
    'agent.code_analyst.capabilities.3': 'مراجعة الكود',
    'agent.code_analyst.capabilities.4': 'شرح المفاهيم البرمجية',
    'agent.code_analyst.systemPrompt': 'أنت مطور برمجيات خبير. تحلل الأكواد وتقدم حلول برمجية فعالة وتشرح المفاهيم التقنية بوضوح.',
    'agent.document_analyzer.name': 'محلل المستندات',
    'agent.document_analyzer.description': 'متخصص في قراءة وتحليل المستندات والملفات',
    'agent.document_analyzer.capabilities.0': 'قراءة المستندات',
    'agent.document_analyzer.capabilities.1': 'تلخيص النصوص',
    'agent.document_analyzer.capabilities.2': 'استخراج المعلومات',
    'agent.document_analyzer.capabilities.3': 'تحليل البيانات',
    'agent.document_analyzer.capabilities.4': 'ترجمة المحتوى',
    'agent.document_analyzer.systemPrompt': 'أنت خبير في تحليل المستندات. تقرأ وتفهم المحتوى وتستخرج المعلومات المهمة وتقدم ملخصات مفيدة.',
    'agent.data_scientist.name': 'عالم البيانات',
    'agent.data_scientist.description': 'خبير في تحليل البيانات والإحصاءات وإنشاء التصورات',
    'agent.data_scientist.capabilities.0': 'تحليل البيانات',
    'agent.data_scientist.capabilities.1': 'الإحصاءات المتقدمة',
    'agent.data_scientist.capabilities.2': 'إنشاء الرسوم البيانية',
    'agent.data_scientist.capabilities.3': 'التنبؤ والنمذجة',
    'agent.data_scientist.capabilities.4': 'تفسير النتائج',
    'agent.data_scientist.systemPrompt': 'أنت عالم بيانات خبير. تحلل البيانات وتستخرج الأنماط والرؤى وتقدم تفسيرات واضحة للنتائج.',
    'agent.creative_writer.name': 'الكاتب المبدع',
    'agent.creative_writer.description': 'متخصص في الكتابة الإبداعية والأدبية',
    'agent.creative_writer.capabilities.0': 'كتابة القصص',
    'agent.creative_writer.capabilities.1': 'الشعر والأدب',
    'agent.creative_writer.capabilities.2': 'السيناريوهات',
    'agent.creative_writer.capabilities.3': 'المحتوى الإبداعي',
    'agent.creative_writer.capabilities.4': 'التحرير والمراجعة',
    'agent.creative_writer.systemPrompt': 'أنت كاتب مبدع موهوب. تكتب نصوص جميلة ومؤثرة وتساعد في تطوير الأفكار الإبداعية.',
    'agent.translator.name': 'المترجم',
    'agent.translator.description': 'خبير في الترجمة بين اللغات المختلفة',
    'agent.translator.capabilities.0': 'الترجمة الفورية',
    'agent.translator.capabilities.1': 'الترجمة الأدبية',
    'agent.translator.capabilities.2': 'الترجمة التقنية',
    'agent.translator.capabilities.3': 'مراجعة الترجمات',
    'agent.translator.capabilities.4': 'تعلم اللغات',
    'agent.translator.systemPrompt': 'أنت مترجم محترف. تترجم النصوص بدقة وتحافظ على المعنى والسياق الثقافي.',
    'agent.researcher.name': 'الباحث',
    'agent.researcher.description': 'متخصص في البحث العلمي والأكاديمي المتعمق',
    'agent.researcher.capabilities.0': 'البحث العلمي',
    'agent.researcher.capabilities.1': 'جمع المراجع',
    'agent.researcher.capabilities.2': 'تحليل الدراسات',
    'agent.researcher.capabilities.3': 'كتابة التقارير',
    'agent.researcher.capabilities.4': 'التحقق من المصادر',
    'agent.researcher.systemPrompt': 'أنت باحث أكاديمي متخصص. تجري بحوث شاملة وتقدم معلومات موثوقة مع ذكر المصادر العلمية.',
    'agent.planner.name': 'المخطط',
    'agent.planner.description': 'خبير في التخطيط وإدارة المشاريع والوقت',
    'agent.planner.capabilities.0': 'وضع الخطط',
    'agent.planner.capabilities.1': 'إدارة المشاريع',
    'agent.planner.capabilities.2': 'تنظيم الوقت',
    'agent.planner.capabilities.3': 'تحديد الأهداف',
    'agent.planner.capabilities.4': 'متابعة التقدم',
    'agent.planner.systemPrompt': 'أنت خبير في التخطيط والتنظيم. تساعد في وضع خطط فعالة وتنظيم المهام والأهداف.',
    'agent.financial_analyst.name': 'المحلل المالي',
    'agent.financial_analyst.description': 'خبير في التحليل المالي والاستثماري',
    'agent.financial_analyst.capabilities.0': 'التحليل المالي',
    'agent.financial_analyst.capabilities.1': 'تقييم الاستثمارات',
    'agent.financial_analyst.capabilities.2': 'التخطيط المالي',
    'agent.financial_analyst.capabilities.3': 'تحليل المخاطر',
    'agent.financial_analyst.capabilities.4': 'النصائح المالية',
    'agent.financial_analyst.systemPrompt': 'أنت محلل مالي خبير. تقدم تحليلات مالية دقيقة ونصائح استثمارية مدروسة.',
    'agent.travel_agent.name': 'وكيل السفر',
    'agent.travel_agent.description': 'متخصص في التخطيط للرحلات والسفر',
    'agent.travel_agent.capabilities.0': 'تخطيط الرحلات',
    'agent.travel_agent.capabilities.1': 'حجز الفنادق',
    'agent.travel_agent.capabilities.2': 'معلومات السفر',
    'agent.travel_agent.capabilities.3': 'النصائح السياحية',
    'agent.travel_agent.capabilities.4': 'إدارة الميزانية',
    'agent.travel_agent.systemPrompt': 'أنت وكيل سفر محترف. تساعد في تخطيط الرحلات وتقدم نصائح سياحية مفيدة.',
    'agent.health_advisor.name': 'المستشار الصحي',
    'agent.health_advisor.description': 'يقدم معلومات ونصائح صحية عامة',
    'agent.health_advisor.capabilities.0': 'النصائح الصحية',
    'agent.health_advisor.capabilities.1': 'معلومات طبية عامة',
    'agent.health_advisor.capabilities.2': 'التغذية والحمية',
    'agent.health_advisor.capabilities.3': 'اللياقة البدنية',
    'agent.health_advisor.capabilities.4': 'الصحة النفسية',
    'agent.health_advisor.systemPrompt': 'أنت مستشار صحي. تقدم معلومات صحية عامة ونصائح للحفاظ على الصحة، مع التأكيد على ضرورة استشارة الطبيب.',
    'agent.education_tutor.name': 'المعلم الخصوصي',
    'agent.education_tutor.description': 'متخصص في التعليم وشرح المفاهيم الأكاديمية',
    'agent.education_tutor.capabilities.0': 'شرح المفاهيم',
    'agent.education_tutor.capabilities.1': 'حل المسائل',
    'agent.education_tutor.capabilities.2': 'التدريس التفاعلي',
    'agent.education_tutor.capabilities.3': 'إعداد الامتحانات',
    'agent.education_tutor.capabilities.4': 'متابعة التقدم',
    'agent.education_tutor.systemPrompt': 'أنت معلم خبير. تشرح المفاهيم بطريقة واضحة ومبسطة وتساعد الطلاب على التعلم والفهم.',
    'agent.live_search_agent.name': 'وكيل البحث المباشر',
    'agent.live_search_agent.description': 'متخصص في البحث المباشر والحصول على معلومات حية ومحدثة',
    'agent.live_search_agent.capabilities.0': 'البحث المباشر',
    'agent.live_search_agent.capabilities.1': 'المعلومات الحية',
    'agent.live_search_agent.capabilities.2': 'أسعار الأسهم',
    'agent.live_search_agent.capabilities.3': 'آخر الأخبار',
    'agent.live_search_agent.capabilities.4': 'البيانات المحدثة',
    'agent.live_search_agent.systemPrompt': 'أنت وكيل بحث متقدم مع وصول مباشر للإنترنت. تحصل على أحدث المعلومات والبيانات الحية.',
    'agent.file_analyzer.name': 'محلل الملفات',
    'agent.file_analyzer.description': 'متخصص في تحليل أنواع مختلفة من الملفات',
    'agent.file_analyzer.capabilities.0': 'تحليل الملفات',
    'agent.file_analyzer.capabilities.1': 'استخراج البيانات',
    'agent.file_analyzer.capabilities.2': 'تحويل الصيغ',
    'agent.file_analyzer.capabilities.3': 'فهرسة المحتوى',
    'agent.file_analyzer.capabilities.4': 'التحقق من الملفات',
    'agent.file_analyzer.systemPrompt': 'أنت خبير في تحليل الملفات. تستطيع قراءة وتحليل أنواع مختلفة من الملفات واستخراج المعلومات منها.',
    'agent.code_executor.name': 'منفذ الأكواد',
    'agent.code_executor.description': 'متخصص في تنفيذ الأكواد البرمجية والعمليات الحسابية',
    'agent.code_executor.capabilities.0': 'تنفيذ الأكواد',
    'agent.code_executor.capabilities.1': 'العمليات الحسابية',
    'agent.code_executor.capabilities.2': 'معالجة البيانات',
    'agent.code_executor.capabilities.3': 'الحوسبة العلمية',
    'agent.code_executor.capabilities.4': 'التحليل الرقمي',
    'agent.code_executor.systemPrompt': 'أنت منفذ أكواد متقدم. تستطيع تنفيذ الأكواد البرمجية وإجراء العمليات الحسابية المعقدة.',
    'features.general-chat.title': 'المحادثة الذكية',
    'features.general-chat.description': 'محادثة طبيعية ومفيدة في جميع المواضيع',
    'features.web-search.title': 'البحث في الإنترنت',
    'features.web-search.description': 'البحث عن أحدث المعلومات والأخبار',
    'features.live-search.title': 'البحث المباشر',
    'features.live-search.description': 'معلومات حية ومحدثة في الوقت الفعلي',
    'features.translation.title': 'الترجمة الفورية',
    'features.translation.description': 'ترجمة دقيقة بين العربية والإنجليزية',
    'features.math-calculator.title': 'الآلة الحاسبة المتقدمة',
    'features.math-calculator.description': 'حل المعادلات والعمليات الحسابية المعقدة',
    'features.image-generation.title': 'إنشاء الصور',
    'features.image-generation.description': 'توليد صور فنية من الوصف النصي',
    'features.creative-writing.title': 'الكتابة الإبداعية',
    'features.creative-writing.description': 'كتابة القصص والشعر والمحتوى الإبداعي',
    'features.content-creation.title': 'إنشاء المحتوى',
    'features.content-creation.description': 'كتابة المقالات والمحتوى التسويقي',
    'features.video-script.title': 'كتابة السيناريوهات',
    'features.video-script.description': 'إعداد نصوص الفيديوهات والعروض',
    'features.image-analysis.title': 'تحليل الصور',
    'features.image-analysis.description': 'فهم وتحليل محتوى الصور والرسوم',
    'features.audio-transcription.title': 'تحويل الصوت لنص',
    'features.audio-transcription.description': 'تحويل التسجيلات الصوتية إلى نص مكتوب',
    'features.video-analysis.title': 'تحليل الفيديو',
    'features.video-analysis.description': 'استخراج المعلومات من مقاطع الفيديو',
    'features.music-generation.title': 'إنشاء الموسيقى',
    'features.music-generation.description': 'توليد المقاطع الموسيقية والألحان',
    'features.code-analysis.title': 'تحليل الأكواد',
    'features.code-analysis.description': 'فهم وتحليل الأكواد البرمجية',
    'features.data-analysis.title': 'تحليل البيانات',
    'features.data-analysis.description': 'تحليل البيانات وإنشاء الرسوم البيانية',
    'features.financial-analysis.title': 'التحليل المالي',
    'features.financial-analysis.description': 'تحليل الأسهم والاستثمارات المالية',
    'features.research-assistant.title': 'مساعد البحث',
    'features.research-assistant.description': 'إجراء البحوث الأكاديمية والعلمية',
    'features.travel-planning.title': 'تخطيط الرحلات',
    'features.travel-planning.description': 'التخطيط للسفر والسياحة',
    'features.health-advisor.title': 'الاستشارة الصحية',
    'features.health-advisor.description': 'نصائح صحية عامة ومعلومات طبية',
    'features.document-analysis.title': 'تحليل المستندات',
    'features.document-analysis.description': 'قراءة وتحليل ملفات PDF والمستندات',
    'features.spreadsheet-analysis.title': 'تحليل جداول البيانات',
    'features.spreadsheet-analysis.description': 'معالجة ملفات Excel وجداول البيانات',
    'features.file-conversion.title': 'تحويل الملفات',
    'features.file-conversion.description': 'تحويل بين صيغ الملفات المختلفة',
    'features.file-organization.title': 'تنظيم الملفات',
    'features.file-organization.description': 'فهرسة وتنظيم الملفات والمجلدات',
    'modal.title': 'نموذجي',
    'modal.message': 'هذا مثال نموذجي. يمكنك تعديله في app/modal.tsx.',
  },
  en: {
    'app.title': 'AI Assistant',
    'login.title': 'Login',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.error': 'Invalid username or password',
    'chat.newChat': 'New Chat',
    'chat.placeholder': 'Type your message here...',
    'chat.send': 'Send',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.logout': 'Logout',
    'features.title': 'Features',
    'features.general': 'General Capabilities',
    'features.content': 'Creative Content Generation',
    'features.media': 'Multimedia Analysis',
    'features.special': 'Special Capabilities',
    'features.files': 'File Management',
    'notFound.title': 'Oops!',
    'notFound.message': 'This screen doesn\'t exist.',
    'notFound.link': 'Go to home screen!',
    'settings.logoutConfirm': 'Are you sure you want to log out?',
    'settings.cancel': 'Cancel',
    'settings.profile.title': 'Profile',
    'settings.profile.notSet': 'Not set',
    'settings.wip': 'Feature in development',
    'settings.languageSelect': 'Choose Language',
    'settings.languageAr': 'العربية',
    'settings.languageEn': 'English',
    'settings.notifications.title': 'Notifications',
    'settings.notifications.subtitle': 'Manage notifications and alerts',
    'settings.privacy.title': 'Privacy and Security',
    'settings.privacy.subtitle': 'Privacy and security settings',
    'settings.about.title': 'About the App',
    'settings.about.subtitle': 'App information and version',
    'settings.about.description': 'AI Assistant\nVersion 1.0.0\n\nAn advanced smart application that provides comprehensive assistance in various fields using advanced artificial intelligence technologies.',
    'settings.header.subtitle': 'Manage app and account settings',
    'settings.user.defaultName': 'User',
    'settings.user.admin': 'System Administrator',
    'settings.user.user': 'User',
    'settings.general': 'General Settings',
    'settings.footer.developedBy': 'Developed by the development team',
    'chat.deleteSession.title': 'Delete Conversation',
    'chat.deleteSession.message': 'Are you sure you want to delete this conversation?',
    'chat.deleteSession.cancel': 'Cancel',
    'chat.deleteSession.delete': 'Delete',
    'chat.permissions.mediaLibrary.title': 'Permission required',
    'chat.permissions.mediaLibrary.message': 'Please grant media library permissions to pick an image.',
    'chat.errors.readDocument.title': 'Error',
    'chat.errors.readDocument.message': 'Could not read the selected document.',
    'chat.permissions.microphone.title': 'Permission required',
    'chat.permissions.microphone.message': 'Please grant microphone permissions to record audio.',
    'chat.errors.startRecording.title': 'Recording Error',
    'chat.errors.startRecording.message': 'Failed to start recording. Please try again.',
    'chat.errors.getRecordingUri.title': 'Recording Error',
    'chat.errors.getRecordingUri.message': 'Failed to get recording URI.',
    'chat.errors.stopRecording.title': 'Recording Error',
    'chat.errors.stopRecording.message': 'Failed to stop recording. Please try again.',
    'chat.permissions.camera.title': 'Permission required',
    'chat.permissions.camera.message': 'Please grant camera permissions to take a photo.',
    'chat.attachments.title': 'Attach a file',
    'chat.attachments.message': 'Choose the attachment type',
    'chat.attachments.gallery': 'Image from Gallery',
    'chat.attachments.camera': 'Take a photo',
    'chat.attachments.file': 'File',
    'chat.attachments.cancel': 'Cancel',
    'features.comingSoon': 'Coming Soon',
    'chat.thinking': 'Thinking...',
    'chat.audioMessage': 'Audio Message',
    'chat.attachedFile': 'Attached File',
    'chat.searchResults': 'Search Results',
    'chat.codeOutput': 'Output:',
    'chat.imagePrompt': 'Prompt:',
    'chat.analysisTitle': 'Analysis of',
    'chat.analysisTypeContent': 'Content',
    'chat.you': 'You',
    'chat.assistant': 'Assistant',
    'agent.general.name': 'General Assistant',
    'agent.general.description': 'A comprehensive smart assistant for general conversation and various inquiries',
    'agent.general.capabilities.0': 'Natural conversation',
    'agent.general.capabilities.1': 'Answering general questions',
    'agent.general.capabilities.2': 'Providing help and advice',
    'agent.general.capabilities.3': 'Simple translation',
    'agent.general.capabilities.4': 'Basic mathematical operations',
    'agent.general.systemPrompt': 'You are a helpful and friendly smart assistant. You answer questions clearly and provide help on various topics.',
    'agent.web_search.name': 'Web Researcher',
    'agent.web_search.description': 'Specialized in searching for modern information on the Internet',
    'agent.web_search.capabilities.0': 'Internet search',
    'agent.web_search.capabilities.1': 'Collecting modern information',
    'agent.web_search.capabilities.2': 'Fact-checking',
    'agent.web_search.capabilities.3': 'Academic research',
    'agent.web_search.capabilities.4': 'Tracking news and events',
    'agent.web_search.systemPrompt': 'You are an expert in searching the Internet. You search for accurate and up-to-date information and present it in an organized manner, citing the sources.',
    'agent.image_generator.name': 'Image Generator',
    'agent.image_generator.description': 'Creates artistic images and designs based on text descriptions',
    'agent.image_generator.capabilities.0': 'Creating images from text',
    'agent.image_generator.capabilities.1': 'Artistic design',
    'agent.image_generator.capabilities.2': 'Illustrations',
    'agent.image_generator.capabilities.3': 'Image editing',
    'agent.image_generator.capabilities.4': 'Logo creation',
    'agent.image_generator.systemPrompt': 'You are a digital artist specializing in creating images. You turn text descriptions into beautiful and expressive images.',
    'agent.code_analyst.name': 'Code Analyst',
    'agent.code_analyst.description': 'An expert in programming, code analysis, and solving technical problems',
    'agent.code_analyst.capabilities.0': 'Code analysis',
    'agent.code_analyst.capabilities.1': 'Bug fixing',
    'agent.code_analyst.capabilities.2': 'Writing programs',
    'agent.code_analyst.capabilities.3': 'Code review',
    'agent.code_analyst.capabilities.4': 'Explaining programming concepts',
    'agent.code_analyst.systemPrompt': 'You are an expert software developer. You analyze codes, provide effective programming solutions, and explain technical concepts clearly.',
    'agent.document_analyzer.name': 'Document Analyzer',
    'agent.document_analyzer.description': 'Specialized in reading and analyzing documents and files',
    'agent.document_analyzer.capabilities.0': 'Reading documents',
    'agent.document_analyzer.capabilities.1': 'Summarizing texts',
    'agent.document_analyzer.capabilities.2': 'Extracting information',
    'agent.document_analyzer.capabilities.3': 'Data analysis',
    'agent.document_analyzer.capabilities.4': 'Content translation',
    'agent.document_analyzer.systemPrompt': 'You are an expert in document analysis. You read and understand the content, extract important information, and provide useful summaries.',
    'agent.data_scientist.name': 'Data Scientist',
    'agent.data_scientist.description': 'An expert in data analysis, statistics, and creating visualizations',
    'agent.data_scientist.capabilities.0': 'Data analysis',
    'agent.data_scientist.capabilities.1': 'Advanced statistics',
    'agent.data_scientist.capabilities.2': 'Creating charts',
    'agent.data_scientist.capabilities.3': 'Prediction and modeling',
    'agent.data_scientist.capabilities.4': 'Interpreting results',
    'agent.data_scientist.systemPrompt': 'You are an expert data scientist. You analyze data, extract patterns and insights, and provide clear interpretations of the results.',
    'agent.creative_writer.name': 'Creative Writer',
    'agent.creative_writer.description': 'Specialized in creative and literary writing',
    'agent.creative_writer.capabilities.0': 'Writing stories',
    'agent.creative_writer.capabilities.1': 'Poetry and literature',
    'agent.creative_writer.capabilities.2': 'Scenarios',
    'agent.creative_writer.capabilities.3': 'Creative content',
    'agent.creative_writer.capabilities.4': 'Editing and proofreading',
    'agent.creative_writer.systemPrompt': 'You are a talented creative writer. You write beautiful and impactful texts and help develop creative ideas.',
    'agent.translator.name': 'Translator',
    'agent.translator.description': 'An expert in translation between different languages',
    'agent.translator.capabilities.0': 'Simultaneous translation',
    'agent.translator.capabilities.1': 'Literary translation',
    'agent.translator.capabilities.2': 'Technical translation',
    'agent.translator.capabilities.3': 'Reviewing translations',
    'agent.translator.capabilities.4': 'Learning languages',
    'agent.translator.systemPrompt': 'You are a professional translator. You translate texts accurately and preserve the meaning and cultural context.',
    'agent.researcher.name': 'Researcher',
    'agent.researcher.description': 'Specialized in in-depth scientific and academic research',
    'agent.researcher.capabilities.0': 'Scientific research',
    'agent.researcher.capabilities.1': 'Collecting references',
    'agent.researcher.capabilities.2': 'Analyzing studies',
    'agent.researcher.capabilities.3': 'Writing reports',
    'agent.researcher.capabilities.4': 'Verifying sources',
    'agent.researcher.systemPrompt': 'You are a specialized academic researcher. You conduct comprehensive research and provide reliable information, citing scientific sources.',
    'agent.planner.name': 'Planner',
    'agent.planner.description': 'An expert in planning and managing projects and time',
    'agent.planner.capabilities.0': 'Making plans',
    'agent.planner.capabilities.1': 'Project management',
    'agent.planner.capabilities.2': 'Time management',
    'agent.planner.capabilities.3': 'Setting goals',
    'agent.planner.capabilities.4': 'Tracking progress',
    'agent.planner.systemPrompt': 'You are an expert in planning and organization. You help create effective plans and organize tasks and goals.',
    'agent.financial_analyst.name': 'Financial Analyst',
    'agent.financial_analyst.description': 'An expert in financial and investment analysis',
    'agent.financial_analyst.capabilities.0': 'Financial analysis',
    'agent.financial_analyst.capabilities.1': 'Evaluating investments',
    'agent.financial_analyst.capabilities.2': 'Financial planning',
    'agent.financial_analyst.capabilities.3': 'Risk analysis',
    'agent.financial_analyst.capabilities.4': 'Financial advice',
    'agent.financial_analyst.systemPrompt': 'You are an expert financial analyst. You provide accurate financial analysis and sound investment advice.',
    'agent.travel_agent.name': 'Travel Agent',
    'agent.travel_agent.description': 'Specialized in planning trips and travel',
    'agent.travel_agent.capabilities.0': 'Trip planning',
    'agent.travel_agent.capabilities.1': 'Hotel reservations',
    'agent.travel_agent.capabilities.2': 'Travel information',
    'agent.travel_agent.capabilities.3': 'Tourist advice',
    'agent.travel_agent.capabilities.4': 'Budget management',
    'agent.travel_agent.systemPrompt': 'You are a professional travel agent. You help plan trips and provide useful tourist advice.',
    'agent.health_advisor.name': 'Health Advisor',
    'agent.health_advisor.description': 'Provides general health information and advice',
    'agent.health_advisor.capabilities.0': 'Health advice',
    'agent.health_advisor.capabilities.1': 'General medical information',
    'agent.health_advisor.capabilities.2': 'Nutrition and diet',
    'agent.health_advisor.capabilities.3': 'Fitness',
    'agent.health_advisor.capabilities.4': 'Mental health',
    'agent.health_advisor.systemPrompt': 'You are a health advisor. You provide general health information and advice on how to maintain health, emphasizing the need to consult a doctor.',
    'agent.education_tutor.name': 'Private Tutor',
    'agent.education_tutor.description': 'Specialized in education and explaining academic concepts',
    'agent.education_tutor.capabilities.0': 'Explaining concepts',
    'agent.education_tutor.capabilities.1': 'Solving problems',
    'agent.education_tutor.capabilities.2': 'Interactive teaching',
    'agent.education_tutor.capabilities.3': 'Exam preparation',
    'agent.education_tutor.capabilities.4': 'Tracking progress',
    'agent.education_tutor.systemPrompt': 'You are an expert teacher. You explain concepts in a clear and simple way and help students learn and understand.',
    'agent.live_search_agent.name': 'Live Search Agent',
    'agent.live_search_agent.description': 'Specialized in live search and obtaining live and updated information',
    'agent.live_search_agent.capabilities.0': 'Live search',
    'agent.live_search_agent.capabilities.1': 'Live information',
    'agent.live_search_agent.capabilities.2': 'Stock prices',
    'agent.live_search_agent.capabilities.3': 'Latest news',
    'agent.live_search_agent.capabilities.4': 'Updated data',
    'agent.live_search_agent.systemPrompt': 'You are an advanced search agent with direct access to the Internet. You get the latest information and live data.',
    'agent.file_analyzer.name': 'File Analyzer',
    'agent.file_analyzer.description': 'Specialized in analyzing different types of files',
    'agent.file_analyzer.capabilities.0': 'File analysis',
    'agent.file_analyzer.capabilities.1': 'Data extraction',
    'agent.file_analyzer.capabilities.2': 'Format conversion',
    'agent.file_analyzer.capabilities.3': 'Content indexing',
    'agent.file_analyzer.capabilities.4': 'File verification',
    'agent.file_analyzer.systemPrompt': 'You are an expert in file analysis. You can read and analyze different types of files and extract information from them.',
    'agent.code_executor.name': 'Code Executor',
    'agent.code_executor.description': 'Specialized in executing code and mathematical operations',
    'agent.code_executor.capabilities.0': 'Code execution',
    'agent.code_executor.capabilities.1': 'Mathematical operations',
    'agent.code_executor.capabilities.2': 'Data processing',
    'agent.code_executor.capabilities.3': 'Scientific computing',
    'agent.code_executor.capabilities.4': 'Numerical analysis',
    'agent.code_executor.systemPrompt': 'You are an advanced code executor. You can execute code and perform complex mathematical operations.',
    'features.general-chat.title': 'Smart Conversation',
    'features.general-chat.description': 'Natural and useful conversation on all topics',
    'features.web-search.title': 'Internet Search',
    'features.web-search.description': 'Search for the latest information and news',
    'features.live-search.title': 'Live Search',
    'features.live-search.description': 'Live and updated information in real time',
    'features.translation.title': 'Instant Translation',
    'features.translation.description': 'Accurate translation between Arabic and English',
    'features.math-calculator.title': 'Advanced Calculator',
    'features.math-calculator.description': 'Solve complex equations and mathematical operations',
    'features.image-generation.title': 'Image Generation',
    'features.image-generation.description': 'Generate artistic images from text descriptions',
    'features.creative-writing.title': 'Creative Writing',
    'features.creative-writing.description': 'Write stories, poetry, and creative content',
    'features.content-creation.title': 'Content Creation',
    'features.content-creation.description': 'Write articles and marketing content',
    'features.video-script.title': 'Script Writing',
    'features.video-script.description': 'Prepare scripts for videos and presentations',
    'features.image-analysis.title': 'Image Analysis',
    'features.image-analysis.description': 'Understand and analyze the content of images and graphics',
    'features.audio-transcription.title': 'Audio to Text',
    'features.audio-transcription.description': 'Convert audio recordings to written text',
    'features.video-analysis.title': 'Video Analysis',
    'features.video-analysis.description': 'Extract information from video clips',
    'features.music-generation.title': 'Music Generation',
    'features.music-generation.description': 'Generate musical clips and melodies',
    'features.code-analysis.title': 'Code Analysis',
    'features.code-analysis.description': 'Understand and analyze source code',
    'features.data-analysis.title': 'Data Analysis',
    'features.data-analysis.description': 'Analyze data and create charts',
    'features.financial-analysis.title': 'Financial Analysis',
    'features.financial-analysis.description': 'Analyze stocks and financial investments',
    'features.research-assistant.title': 'Research Assistant',
    'features.research-assistant.description': 'Conduct academic and scientific research',
    'features.travel-planning.title': 'Trip Planning',
    'features.travel-planning.description': 'Plan for travel and tourism',
    'features.health-advisor.title': 'Health Consultation',
    'features.health-advisor.description': 'General health tips and medical information',
    'features.document-analysis.title': 'Document Analysis',
    'features.document-analysis.description': 'Read and analyze PDF files and documents',
    'features.spreadsheet-analysis.title': 'Spreadsheet Analysis',
    'features.spreadsheet-analysis.description': 'Process Excel files and spreadsheets',
    'features.file-conversion.title': 'File Conversion',
    'features.file-conversion.description': 'Convert between different file formats',
    'features.file-organization.title': 'File Organization',
    'features.file-organization.description': 'Index and organize files and folders',
    'modal.title': 'Modal',
    'modal.message': 'This is an example modal. You can edit it in app/modal.tsx.',
  },
};

export const [LanguageContext, useLanguage] = createContextHook(() => {
  const [language, setLanguageState] = useState<Language>('ar');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const storedLanguage = await AsyncStorage.getItem('language');
      if (storedLanguage === 'ar' || storedLanguage === 'en') {
        setLanguageState(storedLanguage);
      }
    } catch (error) {
      console.error('Failed to load language preference:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem('language', lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Failed to save language preference:', error);
    }
  };

  const t = (key: string, fallback?: string): string => {
    return translations[language][key as keyof typeof translations['en']] || fallback || key;
  };

  return {
    language,
    setLanguage,
    t,
  };
});

